# Generated by Django 3.1.3 on 2021-02-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('item', models.CharField(max_length=200)),
                ('deadline', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
